// Responsive images generated by scripts/optimize-images.sh (`npm run images`).
// Browsers pick the smallest width that fits `sizes`, preferring AVIF and falling back to JPEG.
import siteImages from '../generated/images.json'

/** An image with generated widths: `${path}-${width}.avif|jpg`. */
export type ImageSource = { path: string; width: number; height: number; widths: number[] }

export type SiteImageName = keyof typeof siteImages

/** Images that are part of the site itself (images/originals/ → public/images/generated/). */
export function siteImage(name: SiteImageName): ImageSource {
  return { path: `/images/generated/${name}`, ...siteImages[name] }
}

function srcSet(image: ImageSource, ext: 'avif' | 'jpg'): string {
  return image.widths.map((w) => `${image.path}-${w}.${ext} ${w}w`).join(', ')
}

type ArtDirection = { media: string; image: ImageSource }

type Props = {
  image: ImageSource
  alt: string
  /** Rendered width, e.g. "(max-width: 40rem) 100vw, 24rem". Defaults to full viewport width. */
  sizes?: string
  /** Alternative crops for some viewports, e.g. a portrait image on phones. First match wins. */
  art?: ArtDirection[]
  eager?: boolean
  class?: string
}

export function Picture({ image, alt, sizes = '100vw', art = [], eager, class: className }: Props) {
  const fallbackWidth = image.widths.find((w) => w >= 800) ?? image.widths[image.widths.length - 1]
  return (
    <picture class={className}>
      {art.flatMap(({ media, image: artImage }) => [
        <source
          key={`${artImage.path}-avif`}
          media={media}
          type="image/avif"
          srcset={srcSet(artImage, 'avif')}
          sizes={sizes}
          width={artImage.width}
          height={artImage.height}
        />,
        <source
          key={`${artImage.path}-jpg`}
          media={media}
          type="image/jpeg"
          srcset={srcSet(artImage, 'jpg')}
          sizes={sizes}
          width={artImage.width}
          height={artImage.height}
        />,
      ])}
      <source type="image/avif" srcset={srcSet(image, 'avif')} sizes={sizes} />
      <img
        src={`${image.path}-${fallbackWidth}.jpg`}
        srcset={srcSet(image, 'jpg')}
        sizes={sizes}
        width={image.width}
        height={image.height}
        alt={alt}
        loading={eager ? 'eager' : 'lazy'}
        fetchpriority={eager ? 'high' : undefined}
        decoding="async"
      />
    </picture>
  )
}
