// Responsive images generated by scripts/optimize-images.sh (`npm run images`).
// Browsers pick the smallest width that fits `sizes`, preferring AVIF and falling back to JPEG.
import images from '../generated/images.json'

export type ImageName = keyof typeof images

const BASE = '/images/generated'

export function isImageName(name: string): name is ImageName {
  return name in images
}

function srcSet(name: ImageName, ext: 'avif' | 'jpg'): string {
  return images[name].widths.map((w) => `${BASE}/${name}-${w}.${ext} ${w}w`).join(', ')
}

type ArtDirection = { media: string; name: ImageName }

type Props = {
  name: ImageName
  alt: string
  /** Rendered width, e.g. "(max-width: 40rem) 100vw, 24rem". Defaults to full viewport width. */
  sizes?: string
  /** Alternative crops for some viewports, e.g. a portrait image on phones. First match wins. */
  art?: ArtDirection[]
  eager?: boolean
  class?: string
}

export function Picture({ name, alt, sizes = '100vw', art = [], eager, class: className }: Props) {
  const image = images[name]
  const fallbackWidth = image.widths.find((w) => w >= 800) ?? image.widths[image.widths.length - 1]
  return (
    <picture class={className}>
      {art.flatMap(({ media, name: artName }) => [
        <source
          key={`${artName}-avif`}
          media={media}
          type="image/avif"
          srcset={srcSet(artName, 'avif')}
          sizes={sizes}
          width={images[artName].width}
          height={images[artName].height}
        />,
        <source
          key={`${artName}-jpg`}
          media={media}
          type="image/jpeg"
          srcset={srcSet(artName, 'jpg')}
          sizes={sizes}
          width={images[artName].width}
          height={images[artName].height}
        />,
      ])}
      <source type="image/avif" srcset={srcSet(name, 'avif')} sizes={sizes} />
      <img
        src={`${BASE}/${name}-${fallbackWidth}.jpg`}
        srcset={srcSet(name, 'jpg')}
        sizes={sizes}
        width={image.width}
        height={image.height}
        alt={alt}
        loading={eager ? 'eager' : 'lazy'}
        fetchpriority={eager ? 'high' : undefined}
        decoding="async"
      />
    </picture>
  )
}
